### ISSUE TITLE
 Most popular time of the year to visit, w/ a list of events during that time period. 

### ISSUE THREAD

**Issue by MadamLoki** [MadamLoki/tech-titan-travel-app#11]

**Comment by WilliamSheere** [comment]
**Most popular time of the year to visit, w/ a list of events during that time period**

New York - Summer. (1. Bethpage Air Show, 2. Americade Motorcycle Touring Rally, 3. Bethel Woods Summer Concert Series, 4. Fairport Canal Days, 5. SummerStage) https://www.travelandleisure.com/best-times-to-visit-new-york-city-7567866 | https://www.iloveny.com/blog/post/summer-events-you-dont-want-to-miss-in-new-york-state/

Las Vegas - Fall. (1. Tonopah Star Parties, 2.) Sunset, Stars & Champagne Train, 3.) Beatty Days Festival, 4.) Nevada Day Parade & Celebration, 5.) World Human Powered Speed Challenge) https://www.travelandleisure.com/travel-tips/best-time-to-visit-las-vegas | https://travelnevada.com/events/?start-date=2024-09-09&end-date=2024-11-09

Denver - Winter. (1. Annual Grand Illumination, 2.) Winter X Games, 3.) Ouray Ice Festival, 4.) Steamboat Springs Winter Carnival 5.) Ice-Sculpting Festivals) https://www.uncovercolorado.com/best-times-to-visit-colorado/ | https://www.colorado.com/articles/colorados-iconic-winter-events-celebrations

Washington D.C - Fall. (1. DC Bike Ride, 2.) DC State Fair, 3.) Adams Morgan Day, 4.) Smithsonian Craft2Wear, 5.) Mount Vernon Fall Wine Festival and Sunset Tour) https://travel.usnews.com/Washington_DC/When_To_Visit/ | https://washington.org/visit-dc/fall-events-festivals-washington-dc

Honolulu - Winter. (1. Kilauea Point National Wildlife Refuge, 2.) Volcanoes National Park, 3.) Mt. Mauna Kea Star Gaze 4.) Swim in Sharks Cove, 5.) Snorkeling in Hanauma Bay on Honolulu) https://travel.usnews.com/Honolulu_Oahu_HI/When_To_Visit/ | https://www.ciee.org/in-the-usa/cultural-exchange/winter-activities-hawaii 

Boston - Fall. (1. St. Patrick's Day Parade, 2.) Boston Tea Party Ships & Museum, 3.) Faneuil Hall Marketplace, 4.) Boston Museum of Fine Arts 5.) Boston Public Garden) https://travel.usnews.com/Boston_MA/When_To_Visit/ | https://www.bostonteapartyship.com/things-to-do-in-boston-in-the-fall

Nashville - Winter. (1. Christmas at Gaylord Opryland, 2.) Grand Ole Opry 3.) Nashville Opera, 4.) Gaylord Opryland Resort & Convention, 5.) Belle Meade Historic Site & Winery) https://travel.usnews.com/Nashville_TN/When_To_Visit/ | https://www.visitmusiccity.com/explore-nashville/trip-ideas/winter-bucket-list#

New Orleans - Spring. (1. MARDI GRAS INDIAN TRADITIONS, 2.) Jazz Fest, 3.) French Quarter Festival, 4.) National WWII Museum, 5.) Cinco De Mayo) https://travel.usnews.com/New_Orleans_LA/When_To_Visit/ | https://www.neworleans.com/blog/post/ultimate-spring-travel-guide-to-new-orleans/

Miami - Spring. (1. Wynwood Walls outdoor museum, 2.) Everglades Alligator Farm, 3.) Homestead Cybrarium 4.) Skyviews Miami, 5.) Jungle Island) https://travel.usnews.com/Miami_FL/When_To_Visit/ | https://www.miamiandbeaches.com/things-to-do/attractions/top-miami-attractions

San Diego - Summer. (1. BALBOA PARK, 2.) GASLAMP QUARTER, 3.) SAN DIEGO SEAL TOURS, 4.) WATERFRONT PARK, 5.) LA JOLLA & SAN DIEGO BEACHES DAY TRIPPER TOUR) https://www.sdvr.com/blogs/best-time-to-visit-san-diego | https://www.trolleytours.com/san-diego/summer-things-to-do
