### ISSUE TITLE
weather

### ISSUE THREAD

**Issue by MadamLoki** [MadamLoki/tech-titan-travel-app#3]
scrolling weather bar that changes per city

**Comment by ortizm13** [comment]
New York Weather: https://myperfectweather.com/api/cityinfo/36081New/degF/Average-Weather-in-New-York-New-York-United-States-Year-Round
Las Vegas Weather: https://myperfectweather.com/api/cityinfo/32003Las/degF/Average-Weather-in-Las-Vegas-Nevada-United-States-Year-Round
Denver Weather: https://myperfectweather.com/api/cityinfo/22071New/degF/Average-Weather-in-New-Orleans-Louisiana-United-States-Year-Round
Washington D.C. Weather: https://myperfectweather.com/api/cityinfo/11001Was/degF/Average-Weather-in-Washington-District-of-Columbia-United-States-Year-Round
Honolulu Weather: https://myperfectweather.com/api/cityinfo/15003Hon/degF/Average-Weather-in-Honolulu-Hawaii-United-States-Year-Round
Boston Weather:https://myperfectweather.com/api/cityinfo/25025Bos/degF/Average-Weather-in-Boston-Massachusetts-United-States-Year-Round
Nashville Weather: https://myperfectweather.com/api/cityinfo/37127Nas/degF/Average-Weather-in-Nashville-North-Carolina-United-States-Year-Round
New Orleans Weather:https://myperfectweather.com/api/cityinfo/22071New/degF/Average-Weather-in-New-Orleans-Louisiana-United-States-Year-Round
Miami Weather: https://myperfectweather.com/api/cityinfo/12086Mia/degF/Average-Weather-in-Miami-Florida-United-States-Year-Round
San Diego Weather: https://myperfectweather.com/api/cityinfo/6073San/degF/Average-Weather-in-San-Diego-California-United-States-Year-Round

**Comment by ortizm13** [comment]
Weather API for the top ten cities destinations in the US

**Comment by MadamLoki** [comment]
https://feed.mikle.com/support/add-weather-widget-on-your-website-a-step-by-step-guide/#:~:text=AccuWeather:%20AccuWeather%20provides%20accurate%20weather,?locCode=%5Blocation%20code%5D.

**Comment by MadamLoki** [comment]
https://docs.tomorrow.io/reference/intro/getting-started?_gl=1*1e55609*_gcl_au*NjkzNTAzNzA0LjE3Mjg0MzYzNTQ.
