### ISSUE TITLE
travel checklist idea?

### ISSUE THREAD

**Issue by MadamLoki** [MadamLoki/tech-titan-travel-app#9]

**Comment by ortizm13** [comment]
Going on vacation should be filled with anticipation and excitement, that is why having an essential travel packing checklist is crucial for ensuring smooth and hassle-free experiences. Whether traveling on budget airlines, exploring a new city, lounging on a beach, having the right items packed can make all the difference. 

Example of Travel Checklist Idea:
          CLOTHES
ITEM                                   QTY
Shirts                                    ( )
-Long Sleeve                        ( )
-Short Sleeve                       ( )
Pants/Leggings                    ( )
Short/Skirts                          ( )
Pajamas                               ( )
Shoes/ Sandals                    ( )
Underwear                           ( )
Socks                                    ( )
Swinsuit                                ( )

        ACCESORIES

ITEM                                QTY
Belts                                 ( )
Hat                                   ( )
Sunglasses                       ( )
Tie                                    ( )
Jewelry                             ( )
-Necklace                         ( )
-Earrings                           ( )

     TOILETRIES
ITEM                                 
Toothbrush      
Toothpaste
Shampoo
Conditioner
Hair Brush
Skin care
-Face wash
-Sun Block
-Lotion
-Make up
Vitamins / Prescriptions

 DOCUMENTS
Identification
-Drivers' License
-Passport
Boarding pass
Receipts
Emergency docs
-Health Insurance Card
-Emergency contact
Funds
-Credit / debit card
-Emergency Cash

    GADGETS
Laptop
-Charger
-Hard drive
Camera
-Charger
-SD card
-Extra batteries
Phone
-Charger
Headphones

 HEALTH/MEDICAL
Medications
Prescriptions
Vitamins
Pain Reliever
Insect repellent
Sanitizer

 MISC
Snacks
Keys /House-Car
Books/ Magazines
Water bottle
Pen 
Mini notebook

Here are some important tips when writing a travel check list:
Do not pack items just in case.
Organize your categories so the most important items are at the top.
Remove anything you do not need or wont use 
Before you pack, review your list and note quantities for items you have multiples of.

If you still feel that you need more ideas on how to create a travel checklist or just want to take your packing list to the ultimate level check this Web Site: 



https://www.eaglecreek.com/blogs/articles/what-pack-ultimate-travel-packing-checklist?utm_source=google&utm_id=go_cmp-18402450656_adg-_ad-__dev-c_ext-_prd-_sig-CjwKCAjw9p24BhB_EiwA8ID5Bssh1rYsEwkTDyiYn-VKmQ2UHJIzQ349WBUNiyCN9UPG77UHfSeglhoCt1MQAvD_BwE&gad_source=1&gclid=CjwKCAjw9p24BhB_EiwA8ID5Bssh1rYsEwkTDyiYn-VKmQ2UHJIzQ349WBUNiyCN9UPG77UHfSeglhoCt1MQAvD_BwE

**Comment by ortizm13** [comment]
The travel checklist idea that anyone should have when going on vacation
